CREATE TABLE person (
    person_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_verified INTEGER DEFAULT 0,  
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);